source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'rails', '3.2.5'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtime
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem "jquery-rails"
gem 'mongoid'
gem 'bson_ext'
gem 'yajl-ruby'
gem 'will_paginate'
gem 'rack-ssl'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'validate_url'
gem 'email_validator'
gem 'chronic'
gem 'jquery-rails'
gem 'oauth2_provider', :path => '../..'

group :development, :test do
  gem 'debugger'
  gem 'rspec-rails'
end

group :test do
  gem 'steak'
  gem 'capybara'
  gem 'selenium-client'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'shoulda'
  gem 'factory_girl_rails'
  gem 'webrat'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'watchr'
  gem 'delorean'
  gem 'rspec-set'
end
