source 'http://rubygems.org'
source 'http://gemcutter.org'

gem 'rails', '3.0.4'
gem 'mongoid', '2.0.0.beta.20'
gem 'bson_ext'
gem 'yajl-ruby'
gem 'addressable'
gem 'will_paginate'
gem 'rack-ssl'
gem 'dragonfly'
gem 'rack-cache', :require => 'rack/cache'
gem 'rmagick'
gem 'radius', git: "https://github.com/jlong/radius.git"
gem "bcrypt-ruby", :require => "bcrypt"
gem 'validate_url', '0.1.6'
gem 'email_validator'
gem 'chronic'

group :development, :test do
  gem 'rspec-rails', '2.4.1'
  gem 'cucumber-rails'
  gem 'steak'
  gem 'capybara'
  gem 'selenium-client'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'shoulda'
  gem 'factory_girl_rails', '1.1.beta1'
  gem 'webrat'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'mongoid-rspec'
  gem 'watchr'
  gem 'delorean'
  gem 'rspec-set'
end
