source 'http://rubygems.org'

gem 'rails', '3.0.5'
gem 'mongoid', '2.0.0.beta.20'
gem 'bson_ext'
gem 'yajl-ruby'
gem 'will_paginate'
gem 'rack-ssl'
gem "bcrypt-ruby", :require => "bcrypt"
gem 'validate_url', '0.1.6'
gem 'email_validator'
gem 'chronic'
gem 'jquery-rails'

group :development, :test do
  gem 'debugger'
  gem 'rspec-rails', '2.4.1'
  gem 'steak'
  gem 'capybara'
  gem 'selenium-client'
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'shoulda'
  gem 'factory_girl_rails', '1.1.beta1'
  gem 'webrat'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'database_cleaner'
  gem 'fuubar'
  gem 'watchr'
  gem 'delorean'
  gem 'rspec-set'
end
